<script lang="ts">
  import { page } from "$app/state";
  import AppShell from "$lib/components/AppShell.svelte";
  import OfflineImage from "$lib/components/OfflineImage.svelte";
  import ReturnLink from "$lib/components/ReturnLink.svelte";
  import { parseNovelText } from "$lib/novel-text";
  import { readOfflineText } from "$lib/pixiv-api";
  import type { NovelContent, NovelDetail } from "$lib/types";
  let detail = $state<NovelDetail | null>(null); let content = $state<NovelContent | null>(null); let errorMessage = $state(""); let fontSize = $state(18); let theme = $state<"paper"|"white"|"dark">("paper");
  let id = $derived(page.params.id ?? ""); let key = $derived(`novel-${id}`); let blocks = $derived(content ? parseNovelText(content.text) : []);
  $effect(() => { if (id) void load(id); });
  async function load(expectedId: string) { detail = null; content = null; errorMessage = ""; try { const [detailText, contentText] = await Promise.all([readOfflineText(`novel-${expectedId}`,"detail.json"),readOfflineText(`novel-${expectedId}`,"content.json")]); const nextDetail=JSON.parse(detailText) as NovelDetail; const nextContent=JSON.parse(contentText) as NovelContent; if(nextDetail?.novel?.id!==expectedId || nextContent?.novelId!==expectedId) throw new Error("invalid"); detail=nextDetail;content=nextContent; } catch { errorMessage="无法读取离线小说，缓存可能不完整。"; } }
</script>
<svelte:head><title>{detail?.novel.title || "离线小说"} · PixNya</title></svelte:head>
<AppShell title="离线小说"><main class="offline-novel"><ReturnLink fallback="/offline" label="返回离线资料库" />{#if errorMessage}<section class="state" role="alert">{errorMessage}</section>{:else if !detail || !content}<section class="state">正在读取本地正文…</section>{:else}<header><div class="cover"><OfflineImage entryKey={key} assetNames={["cover.jpg","cover.jpeg","cover.png","cover.webp","cover.gif","cover.avif"]} alt="小说封面" fit="cover" /></div><div><span>离线小说</span><h1>{detail.novel.title}</h1><p>{detail.novel.author.name} · {detail.novel.textLength} 字</p></div><label>字号 <input type="range" min="14" max="28" bind:value={fontSize} /></label><label>背景 <select bind:value={theme}><option value="paper">纸张</option><option value="white">白色</option><option value="dark">夜间</option></select></label></header><article class="reader theme-{theme}" style={`--font:${fontSize}px`}>{#each blocks as block}{#if block.kind==="chapter"}<h2>{block.text}</h2>{:else if block.kind==="page_break"}<hr />{:else if block.kind==="artwork_link"}<div class="embed">文中插画 #{block.id}</div>{:else if block.kind==="uploaded_image"}<div class="embed">文中图片 #{block.id}</div>{:else if block.kind==="external_link"}<span class="embed">{block.label} · {block.url}</span>{:else}<p>{block.text}</p>{/if}{/each}</article>{/if}</main></AppShell>
<style>
  .offline-novel { width: min(900px,100%); margin: 0 auto; padding: 24px 28px 70px; } header { display:grid;grid-template-columns:70px minmax(0,1fr) auto auto;gap:14px;align-items:center;margin-top:18px;padding:14px;border:1px solid var(--line);border-radius:10px;background:white; } .cover{height:92px;overflow:hidden;border-radius:6px;} header span{color:var(--pixiv-blue);font-size:8px;font-weight:700;} h1{margin:6px 0 0;font-size:18px;} header p{margin:5px 0 0;color:var(--muted);font-size:8px;} header label{display:grid;gap:5px;color:var(--muted);font-size:8px;} header input{width:90px;} header select{height:29px;border:1px solid var(--line);border-radius:5px;background:white;} .reader{margin-top:14px;padding:50px clamp(28px,9vw,96px) 80px;border:1px solid var(--line);border-radius:10px;} .theme-paper{color:#33302a;background:#fbf7ec}.theme-white{background:white}.theme-dark{color:#d8d5cf;background:#202326}.reader p{margin:0 0 1.15em;font-size:var(--font);line-height:1.9;white-space:pre-wrap;overflow-wrap:anywhere}.reader h2{margin:2em 0 1.2em;font-size:calc(var(--font)*1.3);text-align:center}.reader hr{width:44%;margin:3em auto;border:0;border-top:1px solid currentColor;opacity:.25}.embed{margin:1.5em 0;padding:13px;color:#6a8798;border:1px dashed currentColor;border-radius:7px;font-size:12px;text-align:center}.state{display:grid;min-height:180px;margin-top:18px;place-items:center;color:var(--muted);border:1px dashed var(--line);border-radius:10px}@media(max-width:620px){.offline-novel{padding:16px 10px 90px}header{grid-template-columns:62px minmax(0,1fr)}header label{grid-column:span 1}.reader{padding:34px 19px 70px}}
</style>
