[package]
name = "pixiv-client-network"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
base64 = "0.22.1"
pixiv-client-domain = { path = "../domain" }
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "json", "rustls", "system-proxy"] }
rcgen = { version = "0.14.8", default-features = false, features = ["aws_lc_rs", "crypto"] }
rustls = { version = "0.23.42", default-features = false, features = ["aws_lc_rs", "std", "tls12"] }
serde.workspace = true
sha2 = "0.10.9"
tokio = { version = "1.53.1", features = ["io-util", "net", "rt", "time"] }
tokio-rustls = "0.26.4"
webpki-roots = "1.0.5"
